/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) outer_sens_mpcc_acados_model_dyn_disc_phi_fun_jac_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_densify CASADI_PREFIX(densify)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fabs CASADI_PREFIX(fabs)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_project CASADI_PREFIX(project)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s12 CASADI_PREFIX(s12)
#define casadi_s13 CASADI_PREFIX(s13)
#define casadi_s14 CASADI_PREFIX(s14)
#define casadi_s15 CASADI_PREFIX(s15)
#define casadi_s16 CASADI_PREFIX(s16)
#define casadi_s17 CASADI_PREFIX(s17)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_sign CASADI_PREFIX(sign)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sign(casadi_real x) { return x<0 ? -1 : x>0 ? 1 : x;}

casadi_real casadi_fabs(casadi_real x) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>0 ? x : -x;
#else
  return fabs(x);
#endif
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_project(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, const casadi_int* sp_y, casadi_real* w) {
  casadi_int ncol_x, ncol_y, i, el;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  for (i=0; i<ncol_x; ++i) {
    for (el=colind_y[i]; el<colind_y[i+1]; ++el) w[row_y[el]] = 0;
    for (el=colind_x[i]; el<colind_x[i+1]; ++el) w[row_x[el]] = x[el];
    for (el=colind_y[i]; el<colind_y[i+1]; ++el) y[el] = w[row_y[el]];
  }
}

#define CASADI_CAST(x,y) ((x) y)

void casadi_densify(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, casadi_int tr) {
  casadi_int nrow_x, ncol_x, i, el;
  const casadi_int *colind_x, *row_x;
  if (!y) return;
  nrow_x = sp_x[0]; ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x+ncol_x+3;
  casadi_clear(y, nrow_x*ncol_x);
  if (!x) return;
  if (tr) {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[i + row_x[el]*ncol_x] = CASADI_CAST(casadi_real, *x++);
      }
    }
  } else {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[row_x[el]] = CASADI_CAST(casadi_real, *x++);
      }
      y += nrow_x;
    }
  }
}

static const casadi_int casadi_s0[6] = {7, 1, 0, 2, 0, 1};
static const casadi_int casadi_s1[8] = {7, 1, 0, 4, 0, 1, 2, 6};
static const casadi_int casadi_s2[6] = {7, 1, 0, 2, 2, 6};
static const casadi_int casadi_s3[8] = {0, 4, 8, 23, 25, 27, 28, 29};
static const casadi_int casadi_s4[5] = {7, 1, 0, 1, 2};
static const casadi_int casadi_s5[9] = 
  {7, 1, 0, 5, 0, 1, 2, 4,
  5};
static const casadi_int casadi_s6[6] = {1, 5, 9, 15, 19, 26};
static const casadi_int casadi_s7[6] = {7, 1, 0, 2, 3, 6};
static const casadi_int casadi_s8[7] = {2, 6, 12, 13, 18, 22, 24};
static const casadi_int casadi_s9[5] = {7, 1, 0, 1, 4};
static const casadi_int casadi_s10[5] = {3, 7, 10, 16, 20};
static const casadi_int casadi_s11[5] = {7, 1, 0, 1, 5};
static const casadi_int casadi_s12[8] = {7, 1, 0, 4, 2, 3, 4, 5};
static const casadi_int casadi_s13[4] = {11, 14, 17, 21};
static const casadi_int casadi_s14[3] = {11, 1, 1};
static const casadi_int casadi_s15[3] = {3, 1, 1};
static const casadi_int casadi_s16[3] = {10, 1, 1};
static const casadi_int casadi_s17[44] = 
  {14, 11, 0, 4, 8, 13, 15, 19,
  23, 25, 27, 28, 29, 30, 3, 5,
  6, 7, 4, 5, 6, 7, 0, 5,
  7, 8, 9, 6, 8, 5, 7, 8,
  9, 5, 7, 8, 9, 1, 9, 2,
  10, 0, 1, 2};

static const casadi_real casadi_zeros[11] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0.};

/* outer_sens_mpcc_acados_model_dyn_disc_phi_fun_jac:(i0[11],i1[3],i2[10])->(o0[11],o1[14x11,30nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, *w01=w+18, w02, w03, w04, w05, w06, w07, w08, w09, w10, w12;
  casadi_real *w13=w+45, w14, w15, w16, w17, w18, w19, w20, w21, w22, w23, w24;
  casadi_real w25, w26, w27, w28, w29, w30, w31, w32, w33, w34, w35, w36;
  casadi_real w37, w38, w39, w40, *w41=w+75, *w42=w+82, *w43=w+112, *w44=w+120, *w45=w+125, *w46=w+127, *w48=w+131, *w49=w+135;
  casadi_real *w50=w+143, *w51=w+145, *w53=w+150, *w54=w+156;
  const casadi_int *cii;
  const casadi_real *cr, *cs, *wr00, *wr01, *wr11;
  /* #0: @0 = input[0][0] */
  wr00 = arg[0] ? arg[0] : casadi_zeros;
  /* #1: @1 = @0[:7] */
  wr01 = wr00+0;
  /* #2: @2 = 0.02 */
  w02 = 2.0000000000000000e-02;
  /* #3: @3 = @0[2] */
  w03 = wr00[2];
  /* #4: @4 = sign(@3) */
  w04 = casadi_sign( w03 );
  /* #5: @3 = fabs(@3) */
  w03 = casadi_fabs( w03 );
  /* #6: @3 = (@4*@3) */
  w03  = (w04*w03);
  /* #7: @5 = @0[3] */
  w05 = wr00[3];
  /* #8: @6 = cos(@5) */
  w06 = cos( w05 );
  /* #9: @7 = (@3*@6) */
  w07  = (w03*w06);
  /* #10: @8 = @0[4] */
  w08 = wr00[4];
  /* #11: @5 = sin(@5) */
  w05 = sin( w05 );
  /* #12: @9 = (@8*@5) */
  w09  = (w08*w05);
  /* #13: @7 = (@7-@9) */
  w07 -= w09;
  /* #14: @9 = (@3*@5) */
  w09  = (w03*w05);
  /* #15: @10 = (@8*@6) */
  w10  = (w08*w06);
  /* #16: @9 = (@9+@10) */
  w09 += w10;
  /* #17: @10 = 0.000815736 */
  w10 = 8.1573587125077600e-04;
  /* #18: @11 = input[2][0] */
  wr11 = arg[2] ? arg[2] : casadi_zeros;
  /* #19: @12 = @11[6] */
  w12 = wr11[6];
  /* #20: @13 = input[1][0] */
  casadi_copy(arg[1], 3, w13);
  /* #21: @14 = @13[0] */
  for (rr=(&w14), cs=w13+0; cs!=w13+1; cs+=1) *rr++ = *cs;
  /* #22: @14 = (@12*@14) */
  w14  = (w12*w14);
  /* #23: @15 = 2.3451 */
  w15 = 2.3451000000000000e+00;
  /* #24: @14 = (@14-@15) */
  w14 -= w15;
  /* #25: @15 = -0.0095 */
  w15 = -9.4999999999999998e-03;
  /* #26: @16 = sq(@3) */
  w16 = casadi_sq( w03 );
  /* #27: @17 = (@15*@16) */
  w17  = (w15*w16);
  /* #28: @14 = (@14-@17) */
  w14 -= w17;
  /* #29: @17 = @11[5] */
  w17 = wr11[5];
  /* #30: @18 = @11[4] */
  w18 = wr11[4];
  /* #31: @19 = @11[3] */
  w19 = wr11[3];
  /* #32: @20 = @0[6] */
  w20 = wr00[6];
  /* #33: @21 = 0.88392 */
  w21 = 8.8392000000000004e-01;
  /* #34: @22 = @0[5] */
  w22 = wr00[5];
  /* #35: @23 = (@21*@22) */
  w23  = (w21*w22);
  /* #36: @23 = (@23+@8) */
  w23 += w08;
  /* #37: @24 = atan2(@23,@3) */
  w24  = atan2(w23,w03);
  /* #38: @24 = (@20-@24) */
  w24  = (w20-w24);
  /* #39: @24 = (@19*@24) */
  w24  = (w19*w24);
  /* #40: @25 = atan(@24) */
  w25 = atan( w24 );
  /* #41: @25 = (@18*@25) */
  w25  = (w18*w25);
  /* #42: @26 = sin(@25) */
  w26 = sin( w25 );
  /* #43: @26 = (@17*@26) */
  w26  = (w17*w26);
  /* #44: @27 = sin(@20) */
  w27 = sin( w20 );
  /* #45: @28 = (@26*@27) */
  w28  = (w26*w27);
  /* #46: @14 = (@14-@28) */
  w14 -= w28;
  /* #47: @28 = 1225.89 */
  w28 = 1.2258869999999999e+03;
  /* #48: @29 = (@8*@22) */
  w29  = (w08*w22);
  /* #49: @29 = (@28*@29) */
  w29  = (w28*w29);
  /* #50: @14 = (@14+@29) */
  w14 += w29;
  /* #51: @14 = (@10*@14) */
  w14  = (w10*w14);
  /* #52: @29 = @11[2] */
  w29 = wr11[2];
  /* #53: @30 = @11[1] */
  w30 = wr11[1];
  /* #54: @31 = @11[0] */
  w31 = wr11[0];
  /* #55: @32 = 1.50876 */
  w32 = 1.5087600000000001e+00;
  /* #56: @33 = (@32*@22) */
  w33  = (w32*w22);
  /* #57: @33 = (@33-@8) */
  w33 -= w08;
  /* #58: @34 = atan2(@33,@3) */
  w34  = atan2(w33,w03);
  /* #59: @34 = (@31*@34) */
  w34  = (w31*w34);
  /* #60: @35 = atan(@34) */
  w35 = atan( w34 );
  /* #61: @35 = (@30*@35) */
  w35  = (w30*w35);
  /* #62: @36 = sin(@35) */
  w36 = sin( w35 );
  /* #63: @36 = (@29*@36) */
  w36  = (w29*w36);
  /* #64: @20 = cos(@20) */
  w20 = cos( w20 );
  /* #65: @37 = (@26*@20) */
  w37  = (w26*w20);
  /* #66: @37 = (@36+@37) */
  w37  = (w36+w37);
  /* #67: @38 = (@3*@22) */
  w38  = (w03*w22);
  /* #68: @38 = (@28*@38) */
  w38  = (w28*w38);
  /* #69: @37 = (@37-@38) */
  w37 -= w38;
  /* #70: @37 = (@10*@37) */
  w37  = (w10*w37);
  /* #71: @38 = 0.000640872 */
  w38 = 6.4087244786166172e-04;
  /* #72: @39 = (@21*@26) */
  w39  = (w21*w26);
  /* #73: @40 = (@39*@20) */
  w40  = (w39*w20);
  /* #74: @36 = (@32*@36) */
  w36  = (w32*w36);
  /* #75: @40 = (@40-@36) */
  w40 -= w36;
  /* #76: @40 = (@38*@40) */
  w40  = (w38*w40);
  /* #77: @36 = @13[1] */
  for (rr=(&w36), cs=w13+1; cs!=w13+2; cs+=1) *rr++ = *cs;
  /* #78: @41 = vertcat(@7, @9, @14, @22, @37, @40, @36) */
  rr=w41;
  *rr++ = w07;
  *rr++ = w09;
  *rr++ = w14;
  *rr++ = w22;
  *rr++ = w37;
  *rr++ = w40;
  *rr++ = w36;
  /* #79: @41 = (@2*@41) */
  for (i=0, rr=w41, cs=w41; i<7; ++i) (*rr++)  = (w02*(*cs++));
  /* #80: @1 = (@1+@41) */
  for (i=0, rr=w01, cr=wr01, cs=w41; i<7; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #81: output[0][0] = @1 */
  casadi_copy(w01, 7, res[0]);
  /* #82: @7 = @0[7] */
  w07 = wr00[7];
  /* #83: @9 = @13[2] */
  for (rr=(&w09), cs=w13+2; cs!=w13+3; cs+=1) *rr++ = *cs;
  /* #84: @9 = (@2*@9) */
  w09  = (w02*w09);
  /* #85: @7 = (@7+@9) */
  w07 += w09;
  /* #86: output[0][1] = @7 */
  if (res[0]) res[0][7] = w07;
  /* #87: output[0][2] = @13 */
  if (res[0]) casadi_copy(w13, 3, res[0]+8);
  /* #88: @42 = zeros(14x11,30nz) */
  casadi_clear(w42, 30);
  /* #89: @43 = ones(14x1,8nz) */
  casadi_fill(w43, 8, 1.);
  /* #90: {@13, @44} = vertsplit(@43) */
  casadi_copy(w43, 3, w13);
  casadi_copy(w43+3, 5, w44);
  /* #91: @45 = @44[:2] */
  for (rr=w45, cs=w44+0; cs!=w44+2; cs+=1) *rr++ = *cs;
  /* #92: @46 = project(@45) */
  casadi_project(w45, casadi_s0, w46, casadi_s1, w);
  /* #93: @47 = 00 */
  /* #94: @7 = @13[0] */
  for (rr=(&w07), cs=w13+0; cs!=w13+1; cs+=1) *rr++ = *cs;
  /* #95: @12 = (@12*@7) */
  w12 *= w07;
  /* #96: @12 = (@10*@12) */
  w12  = (w10*w12);
  /* #97: @7 = @13[1] */
  for (rr=(&w07), cs=w13+1; cs!=w13+2; cs+=1) *rr++ = *cs;
  /* #98: @45 = vertcat(@47, @47, @12, @47, @47, @47, @7) */
  rr=w45;
  *rr++ = w12;
  *rr++ = w07;
  /* #99: @45 = (@2*@45) */
  for (i=0, rr=w45, cs=w45; i<2; ++i) (*rr++)  = (w02*(*cs++));
  /* #100: @48 = project(@45) */
  casadi_project(w45, casadi_s2, w48, casadi_s1, w);
  /* #101: @46 = (@46+@48) */
  for (i=0, rr=w46, cs=w48; i<4; ++i) (*rr++) += (*cs++);
  /* #102: @12 = @13[2] */
  for (rr=(&w12), cs=w13+2; cs!=w13+3; cs+=1) *rr++ = *cs;
  /* #103: @12 = (@2*@12) */
  w12  = (w02*w12);
  /* #104: @43 = vertcat(@46, @12, @13) */
  rr=w43;
  for (i=0, cs=w46; i<4; ++i) *rr++ = *cs++;
  *rr++ = w12;
  for (i=0, cs=w13; i<3; ++i) *rr++ = *cs++;
  /* #105: @49 = @43[:8] */
  for (rr=w49, cs=w43+0; cs!=w43+8; cs+=1) *rr++ = *cs;
  /* #106: (@42[0, 4, 8, 23, 25, 27, 28, 29] = @49) */
  for (cii=casadi_s3, rr=w42, cs=w49; cii!=casadi_s3+8; ++cii, ++cs) rr[*cii] = *cs;
  /* #107: @45 = ones(14x1,2nz) */
  casadi_fill(w45, 2, 1.);
  /* #108: {NULL, @50} = vertsplit(@45) */
  casadi_copy(w45, 2, w50);
  /* #109: @12 = @50[0] */
  for (rr=(&w12), cs=w50+0; cs!=w50+1; cs+=1) *rr++ = *cs;
  /* #110: @44 = project(@12) */
  casadi_project((&w12), casadi_s4, w44, casadi_s5, w);
  /* #111: @12 = @50[0] */
  for (rr=(&w12), cs=w50+0; cs!=w50+1; cs+=1) *rr++ = *cs;
  /* #112: @12 = (@4*@12) */
  w12  = (w04*w12);
  /* #113: @4 = (@4*@12) */
  w04 *= w12;
  /* #114: @12 = (@6*@4) */
  w12  = (w06*w04);
  /* #115: @7 = (@5*@4) */
  w07  = (w05*w04);
  /* #116: @25 = cos(@25) */
  w25 = cos( w25 );
  /* #117: @9 = sq(@23) */
  w09 = casadi_sq( w23 );
  /* #118: @9 = (@9+@16) */
  w09 += w16;
  /* #119: @23 = (@23/@9) */
  w23 /= w09;
  /* #120: @23 = (@23*@4) */
  w23 *= w04;
  /* #121: @23 = (@19*@23) */
  w23  = (w19*w23);
  /* #122: @14 = 1 */
  w14 = 1.;
  /* #123: @24 = sq(@24) */
  w24 = casadi_sq( w24 );
  /* #124: @24 = (@14+@24) */
  w24  = (w14+w24);
  /* #125: @23 = (@23/@24) */
  w23 /= w24;
  /* #126: @23 = (@18*@23) */
  w23  = (w18*w23);
  /* #127: @23 = (@25*@23) */
  w23  = (w25*w23);
  /* #128: @23 = (@17*@23) */
  w23  = (w17*w23);
  /* #129: @37 = (@27*@23) */
  w37  = (w27*w23);
  /* #130: @37 = (-@37) */
  w37 = (- w37 );
  /* #131: @40 = (2.*@3) */
  w40 = (2.* w03 );
  /* #132: @40 = (@40*@4) */
  w40 *= w04;
  /* #133: @15 = (@15*@40) */
  w15 *= w40;
  /* #134: @37 = (@37-@15) */
  w37 -= w15;
  /* #135: @37 = (@10*@37) */
  w37  = (w10*w37);
  /* #136: @15 = (@20*@23) */
  w15  = (w20*w23);
  /* #137: @35 = cos(@35) */
  w35 = cos( w35 );
  /* #138: @40 = sq(@33) */
  w40 = casadi_sq( w33 );
  /* #139: @40 = (@40+@16) */
  w40 += w16;
  /* #140: @33 = (@33/@40) */
  w33 /= w40;
  /* #141: @33 = (@33*@4) */
  w33 *= w04;
  /* #142: @33 = (@31*@33) */
  w33  = (w31*w33);
  /* #143: @34 = sq(@34) */
  w34 = casadi_sq( w34 );
  /* #144: @14 = (@14+@34) */
  w14 += w34;
  /* #145: @33 = (@33/@14) */
  w33 /= w14;
  /* #146: @33 = (@30*@33) */
  w33  = (w30*w33);
  /* #147: @33 = (@35*@33) */
  w33  = (w35*w33);
  /* #148: @33 = (@29*@33) */
  w33  = (w29*w33);
  /* #149: @15 = (@15-@33) */
  w15 -= w33;
  /* #150: @4 = (@22*@4) */
  w04  = (w22*w04);
  /* #151: @4 = (@28*@4) */
  w04  = (w28*w04);
  /* #152: @15 = (@15-@4) */
  w15 -= w04;
  /* #153: @15 = (@10*@15) */
  w15  = (w10*w15);
  /* #154: @23 = (@21*@23) */
  w23  = (w21*w23);
  /* #155: @23 = (@20*@23) */
  w23  = (w20*w23);
  /* #156: @33 = (@32*@33) */
  w33  = (w32*w33);
  /* #157: @23 = (@23+@33) */
  w23 += w33;
  /* #158: @23 = (@38*@23) */
  w23  = (w38*w23);
  /* #159: @51 = vertcat(@12, @7, @37, @47, @15, @23, @47) */
  rr=w51;
  *rr++ = w12;
  *rr++ = w07;
  *rr++ = w37;
  *rr++ = w15;
  *rr++ = w23;
  /* #160: @51 = (@2*@51) */
  for (i=0, rr=w51, cs=w51; i<5; ++i) (*rr++)  = (w02*(*cs++));
  /* #161: @44 = (@44+@51) */
  for (i=0, rr=w44, cs=w51; i<5; ++i) (*rr++) += (*cs++);
  /* #162: @12 = @50[1] */
  for (rr=(&w12), cs=w50+1; cs!=w50+2; cs+=1) *rr++ = *cs;
  /* #163: @52 = zeros(3x1,0nz) */
  /* #164: @53 = vertcat(@44, @12, @52) */
  rr=w53;
  for (i=0, cs=w44; i<5; ++i) *rr++ = *cs++;
  *rr++ = w12;
  /* #165: @54 = @53[:6] */
  for (rr=w54, cs=w53+0; cs!=w53+6; cs+=1) *rr++ = *cs;
  /* #166: (@42[1, 5, 9, 15, 19, 26] = @54) */
  for (cii=casadi_s6, rr=w42, cs=w54; cii!=casadi_s6+6; ++cii, ++cs) rr[*cii] = *cs;
  /* #167: @50 = ones(14x1,2nz) */
  casadi_fill(w50, 2, 1.);
  /* #168: {NULL, @45} = vertsplit(@50) */
  casadi_copy(w50, 2, w45);
  /* #169: @50 = @45[:2] */
  for (rr=w50, cs=w45+0; cs!=w45+2; cs+=1) *rr++ = *cs;
  /* #170: @1 = dense(@50) */
  casadi_densify(w50, casadi_s7, w01, 0);
  /* #171: @12 = @45[0] */
  for (rr=(&w12), cs=w45+0; cs!=w45+1; cs+=1) *rr++ = *cs;
  /* #172: @7 = (@6*@12) */
  w07  = (w06*w12);
  /* #173: @37 = (@8*@7) */
  w37  = (w08*w07);
  /* #174: @37 = (-@37) */
  w37 = (- w37 );
  /* #175: @12 = (@5*@12) */
  w12  = (w05*w12);
  /* #176: @15 = (@3*@12) */
  w15  = (w03*w12);
  /* #177: @37 = (@37-@15) */
  w37 -= w15;
  /* #178: @7 = (@3*@7) */
  w07  = (w03*w07);
  /* #179: @12 = (@8*@12) */
  w12  = (w08*w12);
  /* #180: @7 = (@7-@12) */
  w07 -= w12;
  /* #181: @12 = @45[1] */
  for (rr=(&w12), cs=w45+1; cs!=w45+2; cs+=1) *rr++ = *cs;
  /* #182: @15 = (@19*@12) */
  w15  = (w19*w12);
  /* #183: @15 = (@15/@24) */
  w15 /= w24;
  /* #184: @15 = (@18*@15) */
  w15  = (w18*w15);
  /* #185: @15 = (@25*@15) */
  w15  = (w25*w15);
  /* #186: @15 = (@17*@15) */
  w15  = (w17*w15);
  /* #187: @23 = (@27*@15) */
  w23  = (w27*w15);
  /* #188: @33 = (@20*@12) */
  w33  = (w20*w12);
  /* #189: @33 = (@26*@33) */
  w33  = (w26*w33);
  /* #190: @23 = (@23+@33) */
  w23 += w33;
  /* #191: @23 = (@10*@23) */
  w23  = (w10*w23);
  /* #192: @23 = (-@23) */
  w23 = (- w23 );
  /* #193: @33 = (@20*@15) */
  w33  = (w20*w15);
  /* #194: @12 = (@27*@12) */
  w12  = (w27*w12);
  /* #195: @26 = (@26*@12) */
  w26 *= w12;
  /* #196: @33 = (@33-@26) */
  w33 -= w26;
  /* #197: @33 = (@10*@33) */
  w33  = (w10*w33);
  /* #198: @15 = (@21*@15) */
  w15  = (w21*w15);
  /* #199: @15 = (@20*@15) */
  w15  = (w20*w15);
  /* #200: @39 = (@39*@12) */
  w39 *= w12;
  /* #201: @15 = (@15-@39) */
  w15 -= w39;
  /* #202: @15 = (@38*@15) */
  w15  = (w38*w15);
  /* #203: @44 = vertcat(@37, @7, @23, @47, @33, @15, @47) */
  rr=w44;
  *rr++ = w37;
  *rr++ = w07;
  *rr++ = w23;
  *rr++ = w33;
  *rr++ = w15;
  /* #204: @44 = (@2*@44) */
  for (i=0, rr=w44, cs=w44; i<5; ++i) (*rr++)  = (w02*(*cs++));
  /* #205: @41 = dense(@44) */
  casadi_densify(w44, casadi_s5, w41, 0);
  /* #206: @1 = (@1+@41) */
  for (i=0, rr=w01, cs=w41; i<7; ++i) (*rr++) += (*cs++);
  /* #207: (@42[2, 6, 12, 13, 18, 22, 24] = @1) */
  for (cii=casadi_s8, rr=w42, cs=w01; cii!=casadi_s8+7; ++cii, ++cs) rr[*cii] = *cs;
  /* #208: @37 = ones(14x1,1nz) */
  w37 = 1.;
  /* #209: {NULL, @7} = vertsplit(@37) */
  w07 = w37;
  /* #210: @37 = @7[0] */
  for (rr=(&w37), cs=(&w07)+0; cs!=(&w07)+1; cs+=1) *rr++ = *cs;
  /* #211: @44 = project(@37) */
  casadi_project((&w37), casadi_s9, w44, casadi_s5, w);
  /* #212: @37 = @7[0] */
  for (rr=(&w37), cs=(&w07)+0; cs!=(&w07)+1; cs+=1) *rr++ = *cs;
  /* #213: @5 = (@5*@37) */
  w05 *= w37;
  /* #214: @5 = (-@5) */
  w05 = (- w05 );
  /* #215: @6 = (@6*@37) */
  w06 *= w37;
  /* #216: @9 = (@3/@9) */
  w09  = (w03/w09);
  /* #217: @7 = (@9*@37) */
  w07  = (w09*w37);
  /* #218: @7 = (@19*@7) */
  w07  = (w19*w07);
  /* #219: @7 = (@7/@24) */
  w07 /= w24;
  /* #220: @7 = (@18*@7) */
  w07  = (w18*w07);
  /* #221: @7 = (@25*@7) */
  w07  = (w25*w07);
  /* #222: @7 = (@17*@7) */
  w07  = (w17*w07);
  /* #223: @23 = (@27*@7) */
  w23  = (w27*w07);
  /* #224: @22 = (@22*@37) */
  w22 *= w37;
  /* #225: @22 = (@28*@22) */
  w22  = (w28*w22);
  /* #226: @23 = (@23+@22) */
  w23 += w22;
  /* #227: @23 = (@10*@23) */
  w23  = (w10*w23);
  /* #228: @22 = (@20*@7) */
  w22  = (w20*w07);
  /* #229: @22 = (-@22) */
  w22 = (- w22 );
  /* #230: @40 = (@3/@40) */
  w40  = (w03/w40);
  /* #231: @37 = (@40*@37) */
  w37  = (w40*w37);
  /* #232: @37 = (@31*@37) */
  w37  = (w31*w37);
  /* #233: @37 = (@37/@14) */
  w37 /= w14;
  /* #234: @37 = (@30*@37) */
  w37  = (w30*w37);
  /* #235: @37 = (@35*@37) */
  w37  = (w35*w37);
  /* #236: @37 = (@29*@37) */
  w37  = (w29*w37);
  /* #237: @22 = (@22-@37) */
  w22 -= w37;
  /* #238: @22 = (@10*@22) */
  w22  = (w10*w22);
  /* #239: @37 = (@32*@37) */
  w37  = (w32*w37);
  /* #240: @7 = (@21*@7) */
  w07  = (w21*w07);
  /* #241: @7 = (@20*@7) */
  w07  = (w20*w07);
  /* #242: @37 = (@37-@7) */
  w37 -= w07;
  /* #243: @37 = (@38*@37) */
  w37  = (w38*w37);
  /* #244: @51 = vertcat(@5, @6, @23, @47, @22, @37, @47) */
  rr=w51;
  *rr++ = w05;
  *rr++ = w06;
  *rr++ = w23;
  *rr++ = w22;
  *rr++ = w37;
  /* #245: @51 = (@2*@51) */
  for (i=0, rr=w51, cs=w51; i<5; ++i) (*rr++)  = (w02*(*cs++));
  /* #246: @44 = (@44+@51) */
  for (i=0, rr=w44, cs=w51; i<5; ++i) (*rr++) += (*cs++);
  /* #247: @51 = @44[:5] */
  for (rr=w51, cs=w44+0; cs!=w44+5; cs+=1) *rr++ = *cs;
  /* #248: (@42[3, 7, 10, 16, 20] = @51) */
  for (cii=casadi_s10, rr=w42, cs=w51; cii!=casadi_s10+5; ++cii, ++cs) rr[*cii] = *cs;
  /* #249: @5 = ones(14x1,1nz) */
  w05 = 1.;
  /* #250: {NULL, @6} = vertsplit(@5) */
  w06 = w05;
  /* #251: @5 = @6[0] */
  for (rr=(&w05), cs=(&w06)+0; cs!=(&w06)+1; cs+=1) *rr++ = *cs;
  /* #252: @46 = project(@5) */
  casadi_project((&w05), casadi_s11, w46, casadi_s12, w);
  /* #253: @5 = @6[0] */
  for (rr=(&w05), cs=(&w06)+0; cs!=(&w06)+1; cs+=1) *rr++ = *cs;
  /* #254: @6 = (@21*@5) */
  w06  = (w21*w05);
  /* #255: @9 = (@9*@6) */
  w09 *= w06;
  /* #256: @19 = (@19*@9) */
  w19 *= w09;
  /* #257: @19 = (@19/@24) */
  w19 /= w24;
  /* #258: @18 = (@18*@19) */
  w18 *= w19;
  /* #259: @25 = (@25*@18) */
  w25 *= w18;
  /* #260: @17 = (@17*@25) */
  w17 *= w25;
  /* #261: @27 = (@27*@17) */
  w27 *= w17;
  /* #262: @8 = (@8*@5) */
  w08 *= w05;
  /* #263: @8 = (@28*@8) */
  w08  = (w28*w08);
  /* #264: @27 = (@27+@8) */
  w27 += w08;
  /* #265: @27 = (@10*@27) */
  w27  = (w10*w27);
  /* #266: @8 = (@32*@5) */
  w08  = (w32*w05);
  /* #267: @40 = (@40*@8) */
  w40 *= w08;
  /* #268: @31 = (@31*@40) */
  w31 *= w40;
  /* #269: @31 = (@31/@14) */
  w31 /= w14;
  /* #270: @30 = (@30*@31) */
  w30 *= w31;
  /* #271: @35 = (@35*@30) */
  w35 *= w30;
  /* #272: @29 = (@29*@35) */
  w29 *= w35;
  /* #273: @35 = (@20*@17) */
  w35  = (w20*w17);
  /* #274: @35 = (@29-@35) */
  w35  = (w29-w35);
  /* #275: @3 = (@3*@5) */
  w03 *= w05;
  /* #276: @28 = (@28*@3) */
  w28 *= w03;
  /* #277: @35 = (@35-@28) */
  w35 -= w28;
  /* #278: @10 = (@10*@35) */
  w10 *= w35;
  /* #279: @32 = (@32*@29) */
  w32 *= w29;
  /* #280: @32 = (-@32) */
  w32 = (- w32 );
  /* #281: @21 = (@21*@17) */
  w21 *= w17;
  /* #282: @20 = (@20*@21) */
  w20 *= w21;
  /* #283: @32 = (@32-@20) */
  w32 -= w20;
  /* #284: @38 = (@38*@32) */
  w38 *= w32;
  /* #285: @48 = vertcat(@47, @47, @27, @5, @10, @38, @47) */
  rr=w48;
  *rr++ = w27;
  *rr++ = w05;
  *rr++ = w10;
  *rr++ = w38;
  /* #286: @48 = (@2*@48) */
  for (i=0, rr=w48, cs=w48; i<4; ++i) (*rr++)  = (w02*(*cs++));
  /* #287: @46 = (@46+@48) */
  for (i=0, rr=w46, cs=w48; i<4; ++i) (*rr++) += (*cs++);
  /* #288: @48 = @46[:4] */
  for (rr=w48, cs=w46+0; cs!=w46+4; cs+=1) *rr++ = *cs;
  /* #289: (@42[11, 14, 17, 21] = @48) */
  for (cii=casadi_s13, rr=w42, cs=w48; cii!=casadi_s13+4; ++cii, ++cs) rr[*cii] = *cs;
  /* #290: output[1][0] = @42 */
  casadi_copy(w42, 30, res[1]);
  return 0;
}

CASADI_SYMBOL_EXPORT int outer_sens_mpcc_acados_model_dyn_disc_phi_fun_jac(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int outer_sens_mpcc_acados_model_dyn_disc_phi_fun_jac_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int outer_sens_mpcc_acados_model_dyn_disc_phi_fun_jac_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void outer_sens_mpcc_acados_model_dyn_disc_phi_fun_jac_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int outer_sens_mpcc_acados_model_dyn_disc_phi_fun_jac_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void outer_sens_mpcc_acados_model_dyn_disc_phi_fun_jac_release(int mem) {
}

CASADI_SYMBOL_EXPORT void outer_sens_mpcc_acados_model_dyn_disc_phi_fun_jac_incref(void) {
}

CASADI_SYMBOL_EXPORT void outer_sens_mpcc_acados_model_dyn_disc_phi_fun_jac_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int outer_sens_mpcc_acados_model_dyn_disc_phi_fun_jac_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int outer_sens_mpcc_acados_model_dyn_disc_phi_fun_jac_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real outer_sens_mpcc_acados_model_dyn_disc_phi_fun_jac_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* outer_sens_mpcc_acados_model_dyn_disc_phi_fun_jac_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* outer_sens_mpcc_acados_model_dyn_disc_phi_fun_jac_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* outer_sens_mpcc_acados_model_dyn_disc_phi_fun_jac_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s14;
    case 1: return casadi_s15;
    case 2: return casadi_s16;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* outer_sens_mpcc_acados_model_dyn_disc_phi_fun_jac_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s14;
    case 1: return casadi_s17;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int outer_sens_mpcc_acados_model_dyn_disc_phi_fun_jac_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 10;
  if (sz_res) *sz_res = 4;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 162;
  return 0;
}

CASADI_SYMBOL_EXPORT int outer_sens_mpcc_acados_model_dyn_disc_phi_fun_jac_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 10*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 4*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 162*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
