/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) outer_sens_mpcc_acados_model_dyn_disc_phi_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fabs CASADI_PREFIX(fabs)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_sign CASADI_PREFIX(sign)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sign(casadi_real x) { return x<0 ? -1 : x>0 ? 1 : x;}

casadi_real casadi_fabs(casadi_real x) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>0 ? x : -x;
#else
  return fabs(x);
#endif
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {11, 1, 1};
static const casadi_int casadi_s1[3] = {3, 1, 1};
static const casadi_int casadi_s2[3] = {10, 1, 1};

static const casadi_real casadi_zeros[11] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0.};

/* outer_sens_mpcc_acados_model_dyn_disc_phi_fun:(i0[11],i1[3],i2[10])->(o0[11]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, *w01=w+11, w02, w03, w04, w05, w06, w07, w08, *w10=w+35, w11, w12;
  casadi_real w13, w14, w15, w16, w17, w18, w19, w20, *w21=w+48;
  const casadi_real *cr, *cs, *wr00, *wr01, *wr09;
  /* #0: @0 = input[0][0] */
  wr00 = arg[0] ? arg[0] : casadi_zeros;
  /* #1: @1 = @0[:7] */
  wr01 = wr00+0;
  /* #2: @2 = 0.02 */
  w02 = 2.0000000000000000e-02;
  /* #3: @3 = @0[2] */
  w03 = wr00[2];
  /* #4: @4 = sign(@3) */
  w04 = casadi_sign( w03 );
  /* #5: @3 = fabs(@3) */
  w03 = casadi_fabs( w03 );
  /* #6: @4 = (@4*@3) */
  w04 *= w03;
  /* #7: @3 = @0[3] */
  w03 = wr00[3];
  /* #8: @5 = cos(@3) */
  w05 = cos( w03 );
  /* #9: @6 = (@4*@5) */
  w06  = (w04*w05);
  /* #10: @7 = @0[4] */
  w07 = wr00[4];
  /* #11: @3 = sin(@3) */
  w03 = sin( w03 );
  /* #12: @8 = (@7*@3) */
  w08  = (w07*w03);
  /* #13: @6 = (@6-@8) */
  w06 -= w08;
  /* #14: @3 = (@4*@3) */
  w03  = (w04*w03);
  /* #15: @5 = (@7*@5) */
  w05  = (w07*w05);
  /* #16: @3 = (@3+@5) */
  w03 += w05;
  /* #17: @5 = 0.000815736 */
  w05 = 8.1573587125077600e-04;
  /* #18: @9 = input[2][0] */
  wr09 = arg[2] ? arg[2] : casadi_zeros;
  /* #19: @8 = @9[6] */
  w08 = wr09[6];
  /* #20: @10 = input[1][0] */
  casadi_copy(arg[1], 3, w10);
  /* #21: @11 = @10[0] */
  for (rr=(&w11), cs=w10+0; cs!=w10+1; cs+=1) *rr++ = *cs;
  /* #22: @8 = (@8*@11) */
  w08 *= w11;
  /* #23: @11 = 2.3451 */
  w11 = 2.3451000000000000e+00;
  /* #24: @8 = (@8-@11) */
  w08 -= w11;
  /* #25: @11 = -0.0095 */
  w11 = -9.4999999999999998e-03;
  /* #26: @12 = sq(@4) */
  w12 = casadi_sq( w04 );
  /* #27: @11 = (@11*@12) */
  w11 *= w12;
  /* #28: @8 = (@8-@11) */
  w08 -= w11;
  /* #29: @11 = @9[5] */
  w11 = wr09[5];
  /* #30: @12 = @9[4] */
  w12 = wr09[4];
  /* #31: @13 = @9[3] */
  w13 = wr09[3];
  /* #32: @14 = @0[6] */
  w14 = wr00[6];
  /* #33: @15 = 0.88392 */
  w15 = 8.8392000000000004e-01;
  /* #34: @16 = @0[5] */
  w16 = wr00[5];
  /* #35: @17 = (@15*@16) */
  w17  = (w15*w16);
  /* #36: @17 = (@17+@7) */
  w17 += w07;
  /* #37: @17 = atan2(@17,@4) */
  w17  = atan2(w17,w04);
  /* #38: @17 = (@14-@17) */
  w17  = (w14-w17);
  /* #39: @13 = (@13*@17) */
  w13 *= w17;
  /* #40: @13 = atan(@13) */
  w13 = atan( w13 );
  /* #41: @12 = (@12*@13) */
  w12 *= w13;
  /* #42: @12 = sin(@12) */
  w12 = sin( w12 );
  /* #43: @11 = (@11*@12) */
  w11 *= w12;
  /* #44: @12 = sin(@14) */
  w12 = sin( w14 );
  /* #45: @12 = (@11*@12) */
  w12  = (w11*w12);
  /* #46: @8 = (@8-@12) */
  w08 -= w12;
  /* #47: @12 = 1225.89 */
  w12 = 1.2258869999999999e+03;
  /* #48: @13 = (@7*@16) */
  w13  = (w07*w16);
  /* #49: @13 = (@12*@13) */
  w13  = (w12*w13);
  /* #50: @8 = (@8+@13) */
  w08 += w13;
  /* #51: @8 = (@5*@8) */
  w08  = (w05*w08);
  /* #52: @13 = @9[2] */
  w13 = wr09[2];
  /* #53: @17 = @9[1] */
  w17 = wr09[1];
  /* #54: @18 = @9[0] */
  w18 = wr09[0];
  /* #55: @19 = 1.50876 */
  w19 = 1.5087600000000001e+00;
  /* #56: @20 = (@19*@16) */
  w20  = (w19*w16);
  /* #57: @20 = (@20-@7) */
  w20 -= w07;
  /* #58: @20 = atan2(@20,@4) */
  w20  = atan2(w20,w04);
  /* #59: @18 = (@18*@20) */
  w18 *= w20;
  /* #60: @18 = atan(@18) */
  w18 = atan( w18 );
  /* #61: @17 = (@17*@18) */
  w17 *= w18;
  /* #62: @17 = sin(@17) */
  w17 = sin( w17 );
  /* #63: @13 = (@13*@17) */
  w13 *= w17;
  /* #64: @14 = cos(@14) */
  w14 = cos( w14 );
  /* #65: @17 = (@11*@14) */
  w17  = (w11*w14);
  /* #66: @17 = (@13+@17) */
  w17  = (w13+w17);
  /* #67: @4 = (@4*@16) */
  w04 *= w16;
  /* #68: @12 = (@12*@4) */
  w12 *= w04;
  /* #69: @17 = (@17-@12) */
  w17 -= w12;
  /* #70: @5 = (@5*@17) */
  w05 *= w17;
  /* #71: @17 = 0.000640872 */
  w17 = 6.4087244786166172e-04;
  /* #72: @15 = (@15*@11) */
  w15 *= w11;
  /* #73: @15 = (@15*@14) */
  w15 *= w14;
  /* #74: @19 = (@19*@13) */
  w19 *= w13;
  /* #75: @15 = (@15-@19) */
  w15 -= w19;
  /* #76: @17 = (@17*@15) */
  w17 *= w15;
  /* #77: @15 = @10[1] */
  for (rr=(&w15), cs=w10+1; cs!=w10+2; cs+=1) *rr++ = *cs;
  /* #78: @21 = vertcat(@6, @3, @8, @16, @5, @17, @15) */
  rr=w21;
  *rr++ = w06;
  *rr++ = w03;
  *rr++ = w08;
  *rr++ = w16;
  *rr++ = w05;
  *rr++ = w17;
  *rr++ = w15;
  /* #79: @21 = (@2*@21) */
  for (i=0, rr=w21, cs=w21; i<7; ++i) (*rr++)  = (w02*(*cs++));
  /* #80: @1 = (@1+@21) */
  for (i=0, rr=w01, cr=wr01, cs=w21; i<7; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #81: output[0][0] = @1 */
  casadi_copy(w01, 7, res[0]);
  /* #82: @6 = @0[7] */
  w06 = wr00[7];
  /* #83: @3 = @10[2] */
  for (rr=(&w03), cs=w10+2; cs!=w10+3; cs+=1) *rr++ = *cs;
  /* #84: @2 = (@2*@3) */
  w02 *= w03;
  /* #85: @6 = (@6+@2) */
  w06 += w02;
  /* #86: output[0][1] = @6 */
  if (res[0]) res[0][7] = w06;
  /* #87: output[0][2] = @10 */
  if (res[0]) casadi_copy(w10, 3, res[0]+8);
  return 0;
}

CASADI_SYMBOL_EXPORT int outer_sens_mpcc_acados_model_dyn_disc_phi_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int outer_sens_mpcc_acados_model_dyn_disc_phi_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int outer_sens_mpcc_acados_model_dyn_disc_phi_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void outer_sens_mpcc_acados_model_dyn_disc_phi_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int outer_sens_mpcc_acados_model_dyn_disc_phi_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void outer_sens_mpcc_acados_model_dyn_disc_phi_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void outer_sens_mpcc_acados_model_dyn_disc_phi_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void outer_sens_mpcc_acados_model_dyn_disc_phi_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int outer_sens_mpcc_acados_model_dyn_disc_phi_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int outer_sens_mpcc_acados_model_dyn_disc_phi_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real outer_sens_mpcc_acados_model_dyn_disc_phi_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* outer_sens_mpcc_acados_model_dyn_disc_phi_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* outer_sens_mpcc_acados_model_dyn_disc_phi_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* outer_sens_mpcc_acados_model_dyn_disc_phi_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* outer_sens_mpcc_acados_model_dyn_disc_phi_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int outer_sens_mpcc_acados_model_dyn_disc_phi_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 10;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 55;
  return 0;
}

CASADI_SYMBOL_EXPORT int outer_sens_mpcc_acados_model_dyn_disc_phi_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 10*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 55*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
